/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Bilot1;
import javax.swing.*;
public class App {
    

    public static void main(String[] args) {
     
        SwingUtilities.invokeLater(() -> {
            String studentNumber = JOptionPane.showInputDialog ("Enter Student Number");
            String name = JOptionPane.showInputDialog( "Enter Name");
            String surname = JOptionPane.showInputDialog("enter Surname");
            String email = JOptionPane.showInputDialog( "Enter Email");
            String phoneNumber = JOptionPane.showInputDialog( "Enter Phone Number");
            int mark1 = Integer.parseInt ( JOptionPane.showInputDialog("Enter Mark 1"));
            int mark2 = Integer.parseInt(JOptionPane.showInputDialog("Enter Mark2"));
            int AssignmentMark = Integer.parseInt(JOptionPane.showInputDialog(" Enter Assignment Mark"));
            int examMark = Integer.parseInt(JOptionPane.showInputDialog("Enter exam Mark"));

            //Calculate DP status
            boolean dpStatus = ((mark1 + mark2 + AssignmentMark) / 3) >= 40;

            //Calculate final mark
            double courseworkAverage = (mark1 + mark2 + AssignmentMark) / 3;
            double finalMark = (courseworkAverage * 0.4) + (examMark * 0.6); 
            
            if (finalMark == 0 && finalMark <= 46)
            {
              System.out.println ( "Failed" );
            }  
            else if (finalMark >= 47 && finalMark <= 49)
            {
                System.out.println ( "Sup" );
                        }
            else if (finalMark >= 50 && finalMark <= 74)
            {
                System.out.println ( "Pass" );
            }
            else
            {
                System.out.println ( "Distiction" );
            }
            //Diplay results
            String message = "Students Number:" + studentNumber + "\n"
                + "Name: " + name + " " + surname + "\n"
                + "Email: " + AssignmentMark + "\n"
                + "Mark one: " + mark1 + "\n"
                + "mark two: " + mark2 + "\n"
                + "Assignment mark: " + AssignmentMark + "\n"
                + "DP Status: " + (dpStatus ? "Achieved" : "Not Achived") + "\n"
                + "Final Mark: " + finalMark;
        JOptionPane.showMessageDialog(null, message);
        });
    }
}    
        